merge:
  fast-forward: only
  script:
    - bash .ci/check_maintainership.sh

decrypt:
  rultor_github_secrets.sh: "repo/.ci/rultor_github_secrets.sh.asc"
  rultor_secrets.sh: "repo/.ci/rultor_secrets.sh.asc"
